gui_test.py: fix test_link_discovery for StaleElementReferenceException
Traceback (most recent call last):
  File "/home/hideki/ryu/ryu/tests/topology/gui_client/gui_test.py", line 440, in test_link_discovery
    self._test_link_discovery(links)
  File "/home/hideki/ryu/ryu/tests/topology/gui_client/gui_test.py", line 404, in _test_link_discovery
    ok_(link.name.text in links)
  File "/home/hideki/ryu/.venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 50, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/home/hideki/ryu/.venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py", line 228, in _execute
    return self._parent.execute(command, params)
  File "/home/hideki/ryu/.venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 165, in execute
    self.error_handler.check_response(response)
  File "/home/hideki/ryu/.venv/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 152, in check_response
    raise exception_class(message, screen, stacktrace)
StaleElementReferenceException: Message: u'Element is no longer attached to the DOM' ; Stacktrace: Method fxdriver.cache.getElementAt threw an error in resource://fxdriver/modules/web_element_cache.js